/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeferson Leon
 */
public class FrmTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmTelaPrincipal
     */
    public FrmTelaPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblAltura = new javax.swing.JLabel();
        txtAltura = new javax.swing.JTextField();
        btnDiagnostico = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        lblTituloDiagnotico = new javax.swing.JLabel();
        lblR1 = new javax.swing.JLabel();
        lblR2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica da Gorducha");

        jPanel1.setBackground(new java.awt.Color(153, 102, 255));

        lblTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 255, 0));
        lblTitulo.setText("CLINICA DA DRA. GORDUCHA");

        lblNome.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        lblNome.setText("NOME");

        txtNome.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N

        lblPeso.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        lblPeso.setText("PESO");

        txtPeso.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N

        lblAltura.setFont(new java.awt.Font("Tempus Sans ITC", 1, 11)); // NOI18N
        lblAltura.setText("ALTURA");

        txtAltura.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N

        btnDiagnostico.setBackground(new java.awt.Color(255, 0, 51));
        btnDiagnostico.setForeground(new java.awt.Color(255, 255, 255));
        btnDiagnostico.setText("DIAGNÓSTICO");
        btnDiagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiagnosticoActionPerformed(evt);
            }
        });

        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        lblTituloDiagnotico.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        lblTituloDiagnotico.setForeground(new java.awt.Color(255, 255, 51));
        lblTituloDiagnotico.setText("DIAGNÓSTICO - RESULTADO");

        lblR1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N

        lblR2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloDiagnotico)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDiagnostico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar))
                    .addComponent(lblAltura)
                    .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeso)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitulo))
                .addContainerGap(88, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblR2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addComponent(lblR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPeso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAltura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiagnostico)
                    .addComponent(btnLimpar))
                .addGap(26, 26, 26)
                .addComponent(lblTituloDiagnotico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblR1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblR2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiagnosticoActionPerformed
        String nome = "", r1 = "", r2 = "";
        double peso = 1.2, altura = 0.5, imc = 0;
        DecimalFormat f = new DecimalFormat("0.00");

        nome = txtNome.getText();
        peso = Double.parseDouble(txtPeso.getText());
        altura = Double.parseDouble(txtAltura.getText());

        imc = peso / Math.pow(altura, 2);
        
        r1 = "Olá " + nome + " O seu IMC é " + f.format(imc);
       
        if(imc<16){
            r2 = " Baixo peso muito grave, coma bife de figado ou mondongo!";
        }else if(imc>=16 && imc<17){
            r2 = "Baixo peso grave, coma bastante pão com chimia de uva!";
        }else if(imc >= 17 && imc < 18.50){
            r2 = "Baixo peso, coma muita bastante batata frita!!";
        }else if(imc >= 18.50 && imc < 25){
            r2 = "Peso normal, mas bah tchê - Tomou coscarque!";
        }else if(imc >= 25 && imc < 30){
            r2 = "Sobrepeso, NÃO COMA NADA";
        }else if(imc >= 30 && imc < 35){
            r2 = "Obesidade grau I, alerta você está entrando na zona proibida";
        }else if(imc >= 35 && imc < 40){
            r2 = "Obesidade grau II, entrou na curva da gordice!!";
        }else{
            r2 = "Obesidade grau III - Obesidade Mórbida, Ferrou xiru(a)";
        }
        /*
       Os resultados do IMC são interpretados da seguinte forma:
        Baixo peso muito grave = abaixo de 16 kg/m².
        Baixo peso grave = entre 16 e 16,99 kg/m².
        Baixo peso = entre 17 e 18,49 kg/m².
        Peso normal = entre 18,50 e 24,99 kg/m².
        Sobrepeso = entre 25 e 29,99 kg/m².
        Obesidade grau I = entre 30 e 34,99 kg/m².
        Obesidade grau II = entre 35 e 39,99 kg/m².
        Obesidade grau III (obesidade mórbida) = maior que 40 kg/m².
         */
        lblR1.setText(r1);
        lblR2.setText(r2);
    }//GEN-LAST:event_btnDiagnosticoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       // JOPtionpane  showMessageDialog() showInputDialog() showConfirmDialog();
       if(JOptionPane.showConfirmDialog(null,"Tem certeza que deseja limpar?",
        "Confirme",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
       txtNome.setText(null);
       txtPeso.setText(null);
       txtAltura.setText(null);
       lblR1.setText(null);
       lblR2.setText(null);
       txtNome.requestFocus();
        JOptionPane.showMessageDialog(null, "Limpo com sucesso!!");
       }else{
          JOptionPane.showMessageDialog(null, "Cancelado"); 
       }
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiagnostico;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblR1;
    private javax.swing.JLabel lblR2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloDiagnotico;
    private javax.swing.JTextField txtAltura;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
